"""Add text_notes to audio_notes

Revision ID: 089602b2c740
Revises: 5058e7464528
Create Date: 2025-11-18 19:17:22.559091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089602b2c740'
down_revision: Union[str, Sequence[str], None] = '5058e7464528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_notes', sa.Column('text_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_notes', 'text_notes')
    # ### end Alembic commands ###
